language: go

services:
 - docker

env:
  - DEP_VERSION="0.4.1"

go:
  - '1.10.x'

go_import_path: github.com/rollulus/kafcat

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - make bootstrap

script:
  - make test

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    make publish_github;
    fi
