language: go

services:
 - docker

go:
  - '1.7.x'

go_import_path: github.com/rollulus/kafcat

before_install:
  - go get -u github.com/Masterminds/glide
  - make bootstrap

script:
  - make test

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    make publish_github;
    fi
